# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true

    serializer:
        serialize_null:  true

    routing_loader:
        default_format: json
        include_format: false

    body_listener: true

    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }

    param_fetcher_listener: true

    access_denied_listener:
        json: true

    view:
        view_response_listener: 'force'
        formats:
            json: true

    exception:
        enabled: true
        #exception_controller: 'fos_rest.exception.controller:showAction'